[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.25'
remappings = [
    '@chainlink=lib/chainlink/contracts/src/v0.8/',
    '@openzeppelin=lib/openzeppelin/contracts/',
]

[rpc_endpoints]
ethereum = "${MAINNET_RPC_URL}"